/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package de.gchelper

import de.gchelper.filehelper.*

class App {
    static USER_HOME = System.getProperty('user.home')
    static USER_DOWNLOADS = USER_HOME + File.separator + "Downloads"

    static void main(String[] args) {
    }
}
